[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "ie_bike_model"
author = "Daniel Marranzini"
author-email = "danielalbertomr@student.ie.edu"
description-file = "README.md"
requires = [
    "pandas",
    "sklearn"
]
